# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.QStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.QStackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QStackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QStackedWidget.setObjectName("QStackedWidget")
        self.page1_SW_2 = QtWidgets.QWidget()
        self.page1_SW_2.setObjectName("page1_SW_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page1_SW_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.textBrowser = QtWidgets.QTextBrowser(self.page1_SW_2)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        spacerItem1 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page1_SW_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.page1_SW_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_LE = QtWidgets.QLineEdit(self.page1_SW_2)
        self.project_LE.setObjectName("project_LE")
        self.verticalLayout.addWidget(self.project_LE)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_LE = QtWidgets.QLineEdit(self.page1_SW_2)
        self.file_LE.setObjectName("file_LE")
        self.horizontalLayout_2.addWidget(self.file_LE)
        self.file_TB = QtWidgets.QToolButton(self.page1_SW_2)
        self.file_TB.setObjectName("file_TB")
        self.horizontalLayout_2.addWidget(self.file_TB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.close_PB_0 = QtWidgets.QPushButton(self.page1_SW_2)
        self.close_PB_0.setObjectName("close_PB_0")
        self.horizontalLayout_5.addWidget(self.close_PB_0)
        spacerItem2 = QtWidgets.QSpacerItem(588, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.next_PB_0 = QtWidgets.QPushButton(self.page1_SW_2)
        self.next_PB_0.setObjectName("next_PB_0")
        self.horizontalLayout_5.addWidget(self.next_PB_0)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout_10.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.QStackedWidget.addWidget(self.page1_SW_2)
        self.page2_SW = QtWidgets.QWidget()
        self.page2_SW.setObjectName("page2_SW")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page2_SW)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame = QtWidgets.QFrame(self.page2_SW)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.project_L = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.project_L.setFont(font)
        self.project_L.setObjectName("project_L")
        self.gridLayout_4.addWidget(self.project_L, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.file_L = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.file_L.setFont(font)
        self.file_L.setObjectName("file_L")
        self.gridLayout_5.addWidget(self.file_L, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.errors_L = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.errors_L.setFont(font)
        self.errors_L.setObjectName("errors_L")
        self.horizontalLayout_4.addWidget(self.errors_L)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.angle_SB = QtWidgets.QSpinBox(self.frame)
        self.angle_SB.setObjectName("angle_SB")
        self.horizontalLayout.addWidget(self.angle_SB)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.direct_1_RB = QtWidgets.QRadioButton(self.frame)
        self.direct_1_RB.setObjectName("direct_1_RB")
        self.verticalLayout_7.addWidget(self.direct_1_RB)
        self.direct_2_RB = QtWidgets.QRadioButton(self.frame)
        self.direct_2_RB.setObjectName("direct_2_RB")
        self.verticalLayout_7.addWidget(self.direct_2_RB)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.x_LEFT_max_SP = QtWidgets.QSpinBox(self.frame)
        self.x_LEFT_max_SP.setObjectName("x_LEFT_max_SP")
        self.horizontalLayout_13.addWidget(self.x_LEFT_max_SP)
        self.gridLayout.addLayout(self.horizontalLayout_13, 8, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.x_RIGHT_max_SP = QtWidgets.QSpinBox(self.frame)
        self.x_RIGHT_max_SP.setObjectName("x_RIGHT_max_SP")
        self.horizontalLayout_15.addWidget(self.x_RIGHT_max_SP)
        self.gridLayout.addLayout(self.horizontalLayout_15, 9, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame, 1, 1, 2, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem7, 0, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem8, 1, 0, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem9, 1, 6, 2, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.gridLayout_13.addLayout(self.verticalLayout_6, 1, 4, 3, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem12, 4, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem13, 3, 1, 2, 1)
        self.label_12 = QtWidgets.QLabel(self.page2_SW)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/newPrefix/prezi2.JPG"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 2, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.page2_SW)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.close_PB_1 = QtWidgets.QPushButton(self.page2_SW)
        self.close_PB_1.setObjectName("close_PB_1")
        self.horizontalLayout_6.addWidget(self.close_PB_1)
        spacerItem14 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.back_PB_1 = QtWidgets.QPushButton(self.page2_SW)
        self.back_PB_1.setObjectName("back_PB_1")
        self.horizontalLayout_6.addWidget(self.back_PB_1)
        self.next_PB_1 = QtWidgets.QPushButton(self.page2_SW)
        self.next_PB_1.setObjectName("next_PB_1")
        self.horizontalLayout_6.addWidget(self.next_PB_1)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_2, 5, 0, 1, 7)
        self.label_13 = QtWidgets.QLabel(self.page2_SW)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/photos/img/prezi2.JPG"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 1, 5, 1, 1)
        self.QStackedWidget.addWidget(self.page2_SW)
        self.page3_SW = QtWidgets.QWidget()
        self.page3_SW.setObjectName("page3_SW")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page3_SW)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.plotWidget = MplWidget(self.page3_SW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.plotWidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem15 = QtWidgets.QSpacerItem(20, 288, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem15, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(738, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem16, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.plotWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.page3_SW)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.sum_a_L = QtWidgets.QLabel(self.frame_2)
        self.sum_a_L.setObjectName("sum_a_L")
        self.gridLayout_6.addWidget(self.sum_a_L, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.max_a_L = QtWidgets.QLabel(self.frame_2)
        self.max_a_L.setObjectName("max_a_L")
        self.gridLayout_6.addWidget(self.max_a_L, 2, 1, 1, 1)
        self.max_a_L_des = QtWidgets.QLabel(self.frame_2)
        self.max_a_L_des.setObjectName("max_a_L_des")
        self.gridLayout_6.addWidget(self.max_a_L_des, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 3, 0, 1, 1)
        self.min_a_L = QtWidgets.QLabel(self.frame_2)
        self.min_a_L.setObjectName("min_a_L")
        self.gridLayout_6.addWidget(self.min_a_L, 3, 1, 1, 1)
        self.min_a_L_des = QtWidgets.QLabel(self.frame_2)
        self.min_a_L_des.setObjectName("min_a_L_des")
        self.gridLayout_6.addWidget(self.min_a_L_des, 3, 2, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.page3_SW)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.page3_SW)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem17, 2, 0, 1, 1)
        self.mean_p_L = QtWidgets.QLabel(self.frame_3)
        self.mean_p_L.setObjectName("mean_p_L")
        self.gridLayout_7.addWidget(self.mean_p_L, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.close_PB_2 = QtWidgets.QPushButton(self.page3_SW)
        self.close_PB_2.setObjectName("close_PB_2")
        self.horizontalLayout_8.addWidget(self.close_PB_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem18)
        self.back_PB_2 = QtWidgets.QPushButton(self.page3_SW)
        self.back_PB_2.setObjectName("back_PB_2")
        self.horizontalLayout_8.addWidget(self.back_PB_2)
        self.next_PB_2 = QtWidgets.QPushButton(self.page3_SW)
        self.next_PB_2.setObjectName("next_PB_2")
        self.horizontalLayout_8.addWidget(self.next_PB_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.QStackedWidget.addWidget(self.page3_SW)
        self.page4_SW = QtWidgets.QWidget()
        self.page4_SW.setObjectName("page4_SW")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page4_SW)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.plotWidget_2D = MplWidget(self.page4_SW)
        self.plotWidget_2D.setObjectName("plotWidget_2D")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.plotWidget_2D)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem19 = QtWidgets.QSpacerItem(20, 338, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem19, 0, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(738, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem20, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.plotWidget_2D, 0, 0, 1, 2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.point_HS = QtWidgets.QSlider(self.page4_SW)
        self.point_HS.setOrientation(QtCore.Qt.Horizontal)
        self.point_HS.setObjectName("point_HS")
        self.horizontalLayout_11.addWidget(self.point_HS)
        self.point_SB = QtWidgets.QSpinBox(self.page4_SW)
        self.point_SB.setObjectName("point_SB")
        self.horizontalLayout_11.addWidget(self.point_SB)
        self.gridLayout_12.addLayout(self.horizontalLayout_11, 1, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.page4_SW)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(self.page4_SW)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.label_22 = QtWidgets.QLabel(self.page4_SW)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sum_a3_L = QtWidgets.QLabel(self.page4_SW)
        self.sum_a3_L.setObjectName("sum_a3_L")
        self.verticalLayout_2.addWidget(self.sum_a3_L)
        self.max_a3_L = QtWidgets.QLabel(self.page4_SW)
        self.max_a3_L.setObjectName("max_a3_L")
        self.verticalLayout_2.addWidget(self.max_a3_L)
        self.p_a3_L = QtWidgets.QLabel(self.page4_SW)
        self.p_a3_L.setObjectName("p_a3_L")
        self.verticalLayout_2.addWidget(self.p_a3_L)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.gridLayout_12.addLayout(self.horizontalLayout_10, 2, 0, 2, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem21, 2, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.close_PB_3 = QtWidgets.QPushButton(self.page4_SW)
        self.close_PB_3.setObjectName("close_PB_3")
        self.horizontalLayout_12.addWidget(self.close_PB_3)
        self.back_PB_3 = QtWidgets.QPushButton(self.page4_SW)
        self.back_PB_3.setObjectName("back_PB_3")
        self.horizontalLayout_12.addWidget(self.back_PB_3)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 3, 1, 1, 1)
        self.QStackedWidget.addWidget(self.page4_SW)
        self.gridLayout_9.addWidget(self.QStackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.QStackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Witaj,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">program jest skierowany wyłącznie do analizy danych pobranych z skanera laserowego firmy</span><span style=\" font-size:12pt; font-weight:600;\"> TiM 551</span><span style=\" font-size:12pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Plik zawierające pomiar z urządzenia należy zapisać w formacie:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- .xls lub .xlsc (excel) </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">- .csv.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Następnie należy wybrać plik w programie </span><span style=\" font-size:12pt; font-weight:600;\">TiM 551 road-analizer</span><span style=\" font-size:12pt;\">.</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Nazwa projektu:"))
        self.label.setText(_translate("MainWindow", "Wybierz plik:"))
        self.file_TB.setText(_translate("MainWindow", "..."))
        self.close_PB_0.setText(_translate("MainWindow", "Zamknij"))
        self.next_PB_0.setText(_translate("MainWindow", "Dalej"))
        self.label_6.setText(_translate("MainWindow", "Parametry :"))
        self.label_2.setText(_translate("MainWindow", "Nazwa projektu:"))
        self.project_L.setText(_translate("MainWindow", "Nazwa projektu"))
        self.label_4.setText(_translate("MainWindow", "Plik:"))
        self.file_L.setText(_translate("MainWindow", "Nazwa pliku"))
        self.label_5.setText(_translate("MainWindow", "Liczba błędów :"))
        self.errors_L.setText(_translate("MainWindow", "Nazwa pliku"))
        self.label_11.setText(_translate("MainWindow", "Kąt początkowy pomiaru :"))
        self.label_16.setText(_translate("MainWindow", "Przekrój poprzeczny jezdni:"))
        self.direct_1_RB.setText(_translate("MainWindow", "jednospadkowy"))
        self.direct_2_RB.setText(_translate("MainWindow", "dwuspadkowy"))
        self.label_17.setText(_translate("MainWindow", "Zakreś szerokości mierzonej jezdni [mm]:"))
        self.label_19.setText(_translate("MainWindow", "Lewa strona :"))
        self.label_21.setText(_translate("MainWindow", "Prawa strona"))
        self.close_PB_1.setText(_translate("MainWindow", "Zamknij"))
        self.back_PB_1.setText(_translate("MainWindow", "Powrót"))
        self.next_PB_1.setText(_translate("MainWindow", "Dalej"))
        self.label_8.setText(_translate("MainWindow", "Powierzchnia nierówności"))
        self.label_7.setText(_translate("MainWindow", "Suma wszystkich powierzchni :"))
        self.sum_a_L.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Największa :"))
        self.max_a_L.setText(_translate("MainWindow", "TextLabel"))
        self.max_a_L_des.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Najmniejsza :"))
        self.min_a_L.setText(_translate("MainWindow", "TextLabel"))
        self.min_a_L_des.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "Średnia :"))
        self.mean_p_L.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "Pochylenie jezdni"))
        self.close_PB_2.setText(_translate("MainWindow", "Zamknij"))
        self.back_PB_2.setText(_translate("MainWindow", "Powrót"))
        self.next_PB_2.setText(_translate("MainWindow", "Szczegółowa analiza"))
        self.label_18.setText(_translate("MainWindow", "Pole powierzchni nierówności:"))
        self.label_20.setText(_translate("MainWindow", "Największe odchylenie :"))
        self.label_22.setText(_translate("MainWindow", "Pochylenie poprzeczne :"))
        self.sum_a3_L.setText(_translate("MainWindow", "TextLabel"))
        self.max_a3_L.setText(_translate("MainWindow", "TextLabel"))
        self.p_a3_L.setText(_translate("MainWindow", "TextLabel"))
        self.close_PB_3.setText(_translate("MainWindow", "Zamknij"))
        self.back_PB_3.setText(_translate("MainWindow", "Powrót"))

from mplwidget import MplWidget
import tim_rc
